# The programs run at startup

exec-once = qs -c noctalia-shell --no-duplicate

# Disable the touchpad by default
#exec-once = $scriptsDir/toggle-touchpad.sh

exec-once = hyprctl keyword "device[elan0718:00-04f3:30fd-touchpad]:enabled" false
exec-once = hyprctl keyword "device[elan0718:00-04f3:30fd-mouse]:enabled" false
